version: 2

project_name: adroit

builds:
  - binary: adroit
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE.md
      - README.md

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

changelog:
  use: github
  filters:
    exclude:
      - "^docs:"
      - typo
      - "^chore"
